// Generated by LiveScript 1.2.0
var app, leve1upCtrl;
app = angular.module('leve1up', []);
app.directive('textInput', function($rootScope){
  return {
    restrict: 'E',
    replace: true,
    scope: {
      v: '=for',
      placeholder: '@'
    },
    template: '<div class="ui large input"><input type="text" ng-model="v" placeholder="{{placeholder}}"/></input>',
    link: function(scope, elm, attrs){
      scope.completed = false;
      $rootScope.maxProgress += 1;
      return $(elm).on("change paste keyup", function(){
        if ($(this).val() !== "" && !scope.completed) {
          $rootScope.$apply(function(){
            return $rootScope.progress += 1;
          });
          return scope.completed = true;
        } else if ($(this).val() === "") {
          $rootScope.$apply(function(){
            return $rootScope.progress -= 1;
          });
          return scope.completed = false;
        }
      });
    }
  };
});
app.directive('checkbox', function($rootScope){
  return {
    restrict: 'E',
    replace: true,
    scope: {
      v: '=for',
      label: '@',
      id: '@for'
    },
    template: '<div class="ui big checkbox"><input id="{{id}}" type="checkbox" ng-model="v" /><label for="{{id}}">{{label}}</label></div>',
    link: function(scope, elm, attrs){
      $rootScope.maxProgress += 1;
      return elm.change(function(it){
        if ($(it.target).prop('checked')) {
          return $rootScope.progress += 1;
        } else {
          return $rootScope.progress -= 1;
        }
      });
    }
  };
});
app.directive('progressBar', function(){
  return {
    restrict: 'E',
    replace: true,
    scope: true,
    template: "<div class=\"ui successful progress\">\n  <div class=\"bar\" style=\"width:{{percentage}}%\"></div>\n</div>"
  };
});
leve1upCtrl = function($rootScope){
  $rootScope.progress = 0;
  $rootScope.maxProgress = 0;
  $rootScope.$watch('progress', function(){
    return $rootScope.percentage = $rootScope.progress / $rootScope.maxProgress * 100;
  });
};